<?php
/**
 * @file
 * navigation_region.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function navigation_region_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_acm-siggraph-awards:node/62
  $menu_links['main-menu_acm-siggraph-awards:node/62'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/62',
    'router_path' => 'node/%',
    'link_title' => 'ACM SIGGRAPH Awards',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_acm-siggraph-awards:node/62',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_acm-student-research-competition:node/21
  $menu_links['main-menu_acm-student-research-competition:node/21'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/21',
    'router_path' => 'node/%',
    'link_title' => 'ACM Student Research Competition',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_acm-student-research-competition:node/21',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_acm-student-research-competition:node/63
  $menu_links['main-menu_acm-student-research-competition:node/63'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/63',
    'router_path' => 'node/%',
    'link_title' => 'ACM Student Research Competition',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_acm-student-research-competition:node/63',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_art-gallery:node/18
  $menu_links['main-menu_art-gallery:node/18'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/18',
    'router_path' => 'node/%',
    'link_title' => 'Art Gallery',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_art-gallery:node/18',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_art-gallery:node/64
  $menu_links['main-menu_art-gallery:node/64'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/64',
    'router_path' => 'node/%',
    'link_title' => 'Art Gallery',
    'options' => array(
      'attributes' => array(),
      'alter' => TRUE,
      'identifier' => 'main-menu_art-gallery:node/64',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_art-papers-reviewer-instructions:node/128
  $menu_links['main-menu_art-papers-reviewer-instructions:node/128'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/128',
    'router_path' => 'node/%',
    'link_title' => 'Art Papers Reviewer Instructions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_art-papers-reviewer-instructions:node/128',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_art-papers:node/23',
  );
  // Exported menu link: main-menu_art-papers:node/1496
  $menu_links['main-menu_art-papers:node/1496'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1496',
    'router_path' => 'node/%',
    'link_title' => 'Art Papers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_art-papers:node/1496',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_art-papers:node/23
  $menu_links['main-menu_art-papers:node/23'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/23',
    'router_path' => 'node/%',
    'link_title' => 'Art Papers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_art-papers:node/23',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_attendees-col-1:<nolink>
  $menu_links['main-menu_attendees-col-1:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Attendees-Col-1',
    'options' => array(
      'identifier' => 'main-menu_attendees-col-1:<nolink>',
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
          1 => 'hidden',
        ),
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-attendees:node/2',
  );
  // Exported menu link: main-menu_attendees-col-3:<nolink>
  $menu_links['main-menu_attendees-col-3:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Attendees-Col-3',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 537,
      ),
      'identifier' => 'main-menu_attendees-col-3:<nolink>',
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
          1 => 'hidden',
        ),
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-attendees:node/2',
  );
  // Exported menu link: main-menu_birds-of-a-feather:node/58
  $menu_links['main-menu_birds-of-a-feather:node/58'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/58',
    'router_path' => 'node/%',
    'link_title' => 'Birds of a Feather',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_birds-of-a-feather:node/58',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_birds-of-a-feather:node/70
  $menu_links['main-menu_birds-of-a-feather:node/70'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/70',
    'router_path' => 'node/%',
    'link_title' => 'Birds of a Feather',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_birds-of-a-feather:node/70',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_co-located-events:node/59
  $menu_links['main-menu_co-located-events:node/59'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/59',
    'router_path' => 'node/%',
    'link_title' => 'Co-Located Events',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_co-located-events:node/59',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_computer-animation-festival:node/35
  $menu_links['main-menu_computer-animation-festival:node/35'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/35',
    'router_path' => 'node/%',
    'link_title' => 'Computer Animation Festival',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_computer-animation-festival:node/35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_computer-animation-festival:node/36
  $menu_links['main-menu_computer-animation-festival:node/36'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/36',
    'router_path' => 'node/%',
    'link_title' => 'Computer Animation Festival',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_computer-animation-festival:node/36',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_conference-overview:http://null
  $menu_links['main-menu_conference-overview:http://null'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://null',
    'router_path' => '',
    'link_title' => 'Conference Overview',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_conference-overview:http://null',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-1:<nolink>',
  );
  // Exported menu link: main-menu_contact-the-media-office:node/61
  $menu_links['main-menu_contact-the-media-office:node/61'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/61',
    'router_path' => 'node/%',
    'link_title' => 'Contact the Media Office',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_contact-the-media-office:node/61',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-the-media:node/5',
  );
  // Exported menu link: main-menu_courses:node/19
  $menu_links['main-menu_courses:node/19'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/19',
    'router_path' => 'node/%',
    'link_title' => 'Courses',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_courses:node/19',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_courses:node/71
  $menu_links['main-menu_courses:node/71'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/71',
    'router_path' => 'node/%',
    'link_title' => 'Courses',
    'options' => array(
      'attributes' => array(),
      'alter' => TRUE,
      'identifier' => 'main-menu_courses:node/71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_dailies:node/15
  $menu_links['main-menu_dailies:node/15'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/15',
    'router_path' => 'node/%',
    'link_title' => 'Dailies',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_dailies:node/15',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_dailies:node/77
  $menu_links['main-menu_dailies:node/77'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/77',
    'router_path' => 'node/%',
    'link_title' => 'Dailies',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_dailies:node/77',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_education-focus:node/3977
  $menu_links['main-menu_education-focus:node/3977'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3977',
    'router_path' => 'node/%',
    'link_title' => 'Education Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_education-focus:node/3977',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_education-focus:node/3979
  $menu_links['main-menu_education-focus:node/3979'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3979',
    'router_path' => 'node/%',
    'link_title' => 'Education Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_education-focus:node/3979',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_electronic-slides-and-still-images:node/27
  $menu_links['main-menu_electronic-slides-and-still-images:node/27'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/27',
    'router_path' => 'node/%',
    'link_title' => 'Electronic Slides and Still Images',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_electronic-slides-and-still-images:node/27',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_speaker-preparation:node/24',
  );
  // Exported menu link: main-menu_emerging-technologies:node/33
  $menu_links['main-menu_emerging-technologies:node/33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/33',
    'router_path' => 'node/%',
    'link_title' => 'Emerging Technologies',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_emerging-technologies:node/33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_emerging-technologies:node/72
  $menu_links['main-menu_emerging-technologies:node/72'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/72',
    'router_path' => 'node/%',
    'link_title' => 'Emerging Technologies',
    'options' => array(
      'attributes' => array(),
      'alter' => TRUE,
      'identifier' => 'main-menu_emerging-technologies:node/72',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_english-review-service:node/44
  $menu_links['main-menu_english-review-service:node/44'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/44',
    'router_path' => 'node/%',
    'link_title' => 'English Review Service',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_english-review-service:node/44',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_international-resources:node/43',
  );
  // Exported menu link: main-menu_equipment-insurance:node/31
  $menu_links['main-menu_equipment-insurance:node/31'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/31',
    'router_path' => 'node/%',
    'link_title' => 'Equipment Insurance',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_equipment-insurance:node/31',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_ethics-of-review:node/38
  $menu_links['main-menu_ethics-of-review:node/38'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/38',
    'router_path' => 'node/%',
    'link_title' => 'Ethics of Review',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_ethics-of-review:node/38',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_technical-papers:node/37',
  );
  // Exported menu link: main-menu_ethics-of-the-art-papers-review-process:node/127
  $menu_links['main-menu_ethics-of-the-art-papers-review-process:node/127'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/127',
    'router_path' => 'node/%',
    'link_title' => 'Ethics of the Art Papers Review Process',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_ethics-of-the-art-papers-review-process:node/127',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_art-papers:node/23',
  );
  // Exported menu link: main-menu_exhibiting-at-siggraph-2015:node/3978
  $menu_links['main-menu_exhibiting-at-siggraph-2015:node/3978'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3978',
    'router_path' => 'node/%',
    'link_title' => 'Exhibiting at SIGGRAPH 2015',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_exhibiting-at-siggraph-2015:node/3978',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-exhibitors--advertisers:node/6',
  );
  // Exported menu link: main-menu_exhibition:node/73
  $menu_links['main-menu_exhibition:node/73'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/73',
    'router_path' => 'node/%',
    'link_title' => 'Exhibition',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_exhibition:node/73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_exhibitor-tech-talks:node/74
  $menu_links['main-menu_exhibitor-tech-talks:node/74'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/74',
    'router_path' => 'node/%',
    'link_title' => 'Exhibitor Tech Talks',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_exhibitor-tech-talks:node/74',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_exhibits-fast-forward:node/1022
  $menu_links['main-menu_exhibits-fast-forward:node/1022'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1022',
    'router_path' => 'node/%',
    'link_title' => 'Exhibits Fast Forward',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_exhibits-fast-forward:node/1022',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
    'parent_identifier' => 'main-menu_programs--events:<nolink>',
  );
  // Exported menu link: main-menu_for-attendees:node/2
  $menu_links['main-menu_for-attendees:node/2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/2',
    'router_path' => 'node/%',
    'link_title' => 'For Attendees',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 385,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'for-attendees',
        ),
      ),
      'identifier' => 'main-menu_for-attendees:node/2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_for-exhibitors--advertisers:node/6
  $menu_links['main-menu_for-exhibitors--advertisers:node/6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/6',
    'router_path' => 'node/%',
    'link_title' => 'For Exhibitors & Advertisers',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 389,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'for-exhibitors-advertisers',
        ),
      ),
      'identifier' => 'main-menu_for-exhibitors--advertisers:node/6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_for-presenters:node/16
  $menu_links['main-menu_for-presenters:node/16'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/16',
    'router_path' => 'node/%',
    'link_title' => 'For Presenters',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_for-presenters:node/16',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_for-submitters:node/3
  $menu_links['main-menu_for-submitters:node/3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3',
    'router_path' => 'node/%',
    'link_title' => 'For Submitters',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 386,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'for-submitters',
        ),
      ),
      'identifier' => 'main-menu_for-submitters:node/3',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_for-the-media:node/5
  $menu_links['main-menu_for-the-media:node/5'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/5',
    'router_path' => 'node/%',
    'link_title' => 'For the Media',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 388,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'for-the-media',
        ),
      ),
      'identifier' => 'main-menu_for-the-media:node/5',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_for-volunteers:node/3982
  $menu_links['main-menu_for-volunteers:node/3982'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3982',
    'router_path' => 'node/%',
    'link_title' => 'For Volunteers',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'for-volunteers',
        ),
      ),
      'identifier' => 'main-menu_for-volunteers:node/3982',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_frequently-asked-questions:node/46
  $menu_links['main-menu_frequently-asked-questions:node/46'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/46',
    'router_path' => 'node/%',
    'link_title' => 'Frequently Asked Questions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_frequently-asked-questions:node/46',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_international-resources:node/43',
  );
  // Exported menu link: main-menu_frequently-asked-questions:node/54
  $menu_links['main-menu_frequently-asked-questions:node/54'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/54',
    'router_path' => 'node/%',
    'link_title' => 'Frequently Asked Questions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_frequently-asked-questions:node/54',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_student-volunteers:node/48',
  );
  // Exported menu link: main-menu_future-conference-committees:http://www.siggraph.org/participate/volunteer/conference-volunteer-form
  $menu_links['main-menu_future-conference-committees:http://www.siggraph.org/participate/volunteer/conference-volunteer-form'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://www.siggraph.org/participate/volunteer/conference-volunteer-form',
    'router_path' => '',
    'link_title' => 'Future Conference Committees',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_future-conference-committees:http://www.siggraph.org/participate/volunteer/conference-volunteer-form',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-volunteers:node/3982',
  );
  // Exported menu link: main-menu_games-focus:node/34
  $menu_links['main-menu_games-focus:node/34'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/34',
    'router_path' => 'node/%',
    'link_title' => 'Games Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_games-focus:node/34',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_games-focus:node/3980
  $menu_links['main-menu_games-focus:node/3980'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3980',
    'router_path' => 'node/%',
    'link_title' => 'Games Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_games-focus:node/3980',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_graphicsnet:node/57
  $menu_links['main-menu_graphicsnet:node/57'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/57',
    'router_path' => 'node/%',
    'link_title' => 'GraphicsNet',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_graphicsnet:node/57',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-volunteers:node/3982',
  );
  // Exported menu link: main-menu_home:<front>
  $menu_links['main-menu_home:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Home',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'fa',
          1 => 'fa-home',
          2 => 'home-link',
        ),
      ),
      'identifier' => 'main-menu_home:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: main-menu_hotels:node/116
  $menu_links['main-menu_hotels:node/116'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/116',
    'router_path' => 'node/%',
    'link_title' => 'Hotels',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_hotels:node/116',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_information--planning:<nolink>',
  );
  // Exported menu link: main-menu_how-to-apply-for-a-visa:node/45
  $menu_links['main-menu_how-to-apply-for-a-visa:node/45'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/45',
    'router_path' => 'node/%',
    'link_title' => 'How to Apply for a Visa',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_how-to-apply-for-a-visa:node/45',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_international-resources:node/43',
  );
  // Exported menu link: main-menu_information--planning:<nolink>
  $menu_links['main-menu_information--planning:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Information & Planning',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 0,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
        ),
      ),
      'identifier' => 'main-menu_information--planning:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-attendees:node/2',
  );
  // Exported menu link: main-menu_international-resources:node/1497
  $menu_links['main-menu_international-resources:node/1497'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1497',
    'router_path' => 'node/%',
    'link_title' => 'International Resources',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_international-resources:node/1497',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_international-resources:node/43
  $menu_links['main-menu_international-resources:node/43'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/43',
    'router_path' => 'node/%',
    'link_title' => 'International Resources',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_international-resources:node/43',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_international-resources:node/55
  $menu_links['main-menu_international-resources:node/55'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/55',
    'router_path' => 'node/%',
    'link_title' => 'International Resources',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_international-resources:node/55',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-volunteers:node/3982',
  );
  // Exported menu link: main-menu_job-fair:node/1024
  $menu_links['main-menu_job-fair:node/1024'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1024',
    'router_path' => 'node/%',
    'link_title' => 'Job Fair',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_job-fair:node/1024',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_job-seekers--casual-networkers:node/350
  $menu_links['main-menu_job-seekers--casual-networkers:node/350'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/350',
    'router_path' => 'node/%',
    'link_title' => 'Job Seekers & Casual Networkers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_job-seekers--casual-networkers:node/350',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_job-fair:node/1024',
  );
  // Exported menu link: main-menu_logos--guidelines:node/120
  $menu_links['main-menu_logos--guidelines:node/120'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/120',
    'router_path' => 'node/%',
    'link_title' => 'Logos & Guidelines',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_logos--guidelines:node/120',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-the-media:node/5',
  );
  // Exported menu link: main-menu_los-angeles:node/112
  $menu_links['main-menu_los-angeles:node/112'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/112',
    'router_path' => 'node/%',
    'link_title' => 'Los Angeles',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_los-angeles:node/112',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_information--planning:<nolink>',
  );
  // Exported menu link: main-menu_making--siggraph-2015:node/3976
  $menu_links['main-menu_making--siggraph-2015:node/3976'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3976',
    'router_path' => 'node/%',
    'link_title' => 'Making @ SIGGRAPH 2015',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_making--siggraph-2015:node/3976',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-2:<nolink>',
  );
  // Exported menu link: main-menu_mobile-focus:node/3975
  $menu_links['main-menu_mobile-focus:node/3975'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3975',
    'router_path' => 'node/%',
    'link_title' => 'Mobile Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_mobile-focus:node/3975',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_mobile-focus:node/3981
  $menu_links['main-menu_mobile-focus:node/3981'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3981',
    'router_path' => 'node/%',
    'link_title' => 'Mobile Focus',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_mobile-focus:node/3981',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_movies-in-presentations:node/28
  $menu_links['main-menu_movies-in-presentations:node/28'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/28',
    'router_path' => 'node/%',
    'link_title' => 'Movies in Presentations',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_movies-in-presentations:node/28',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_speaker-preparation:node/24',
  );
  // Exported menu link: main-menu_news-releases:node/123
  $menu_links['main-menu_news-releases:node/123'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/123',
    'router_path' => 'node/%',
    'link_title' => 'News Releases',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_news-releases:node/123',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-the-media:node/5',
  );
  // Exported menu link: main-menu_panels:node/75
  $menu_links['main-menu_panels:node/75'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/75',
    'router_path' => 'node/%',
    'link_title' => 'Panels',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_panels:node/75',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_panels:node/79
  $menu_links['main-menu_panels:node/79'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/79',
    'router_path' => 'node/%',
    'link_title' => 'Panels',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_panels:node/79',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_posters:node/20
  $menu_links['main-menu_posters:node/20'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/20',
    'router_path' => 'node/%',
    'link_title' => 'Posters',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_posters:node/20',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_posters:node/22
  $menu_links['main-menu_posters:node/22'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/22',
    'router_path' => 'node/%',
    'link_title' => 'Posters',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_posters:node/22',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_production-sessions:node/110
  $menu_links['main-menu_production-sessions:node/110'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/110',
    'router_path' => 'node/%',
    'link_title' => 'Production Sessions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_production-sessions:node/110',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_production-sessions:node/111
  $menu_links['main-menu_production-sessions:node/111'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/111',
    'router_path' => 'node/%',
    'link_title' => 'Production Sessions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_production-sessions:node/111',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_programs--events:<nolink>
  $menu_links['main-menu_programs--events:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Programs & Events',
    'options' => array(
      'menu_views' => array(
        'name' => FALSE,
        'display' => FALSE,
        'arguments' => '',
        'mlid' => 0,
      ),
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
        ),
      ),
      'identifier' => 'main-menu_programs--events:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-attendees:node/2',
  );
  // Exported menu link: main-menu_publication-requirements:node/39
  $menu_links['main-menu_publication-requirements:node/39'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/39',
    'router_path' => 'node/%',
    'link_title' => 'Publication Requirements',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_publication-requirements:node/39',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_technical-papers:node/37',
  );
  // Exported menu link: main-menu_real-time-live:node/68
  $menu_links['main-menu_real-time-live:node/68'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/68',
    'router_path' => 'node/%',
    'link_title' => 'Real-Time Live!',
    'options' => array(
      'attributes' => array(),
      'alter' => TRUE,
      'identifier' => 'main-menu_real-time-live:node/68',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_real-time-live:node/69
  $menu_links['main-menu_real-time-live:node/69'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/69',
    'router_path' => 'node/%',
    'link_title' => 'Real-Time Live!',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_real-time-live:node/69',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_reasons-to-attend-siggraph:node/1802
  $menu_links['main-menu_reasons-to-attend-siggraph:node/1802'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1802',
    'router_path' => 'node/%',
    'link_title' => 'Reasons to Attend SIGGRAPH',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_reasons-to-attend-siggraph:node/1802',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_information--planning:<nolink>',
  );
  // Exported menu link: main-menu_recognition-policy-for-presenters--volunteers:node/17
  $menu_links['main-menu_recognition-policy-for-presenters--volunteers:node/17'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/17',
    'router_path' => 'node/%',
    'link_title' => 'Recognition Policy for Presenters & Volunteers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_recognition-policy-for-presenters--volunteers:node/17',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-presenters:node/16',
  );
  // Exported menu link: main-menu_registration:node/93
  $menu_links['main-menu_registration:node/93'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/93',
    'router_path' => 'node/%',
    'link_title' => 'Registration',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_registration:node/93',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_information--planning:<nolink>',
  );
  // Exported menu link: main-menu_representative-image-guidelines:node/29
  $menu_links['main-menu_representative-image-guidelines:node/29'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/29',
    'router_path' => 'node/%',
    'link_title' => 'Representative Image Guidelines',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_representative-image-guidelines:node/29',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_reviewer-instructions:node/41
  $menu_links['main-menu_reviewer-instructions:node/41'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/41',
    'router_path' => 'node/%',
    'link_title' => 'Reviewer Instructions',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_reviewer-instructions:node/41',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_technical-papers:node/37',
  );
  // Exported menu link: main-menu_session-room-equipment:node/26
  $menu_links['main-menu_session-room-equipment:node/26'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/26',
    'router_path' => 'node/%',
    'link_title' => 'Session Room Equipment',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_session-room-equipment:node/26',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_speaker-preparation:node/24',
  );
  // Exported menu link: main-menu_siggraph-in-the-news:node/373
  $menu_links['main-menu_siggraph-in-the-news:node/373'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/373',
    'router_path' => 'node/%',
    'link_title' => 'SIGGRAPH in the News',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_siggraph-in-the-news:node/373',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-the-media:node/5',
  );
  // Exported menu link: main-menu_siggraph-media-blog:http://siggraphmediablog.blogspot.com/
  $menu_links['main-menu_siggraph-media-blog:http://siggraphmediablog.blogspot.com/'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://siggraphmediablog.blogspot.com/',
    'router_path' => '',
    'link_title' => 'SIGGRAPH Media Blog',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_siggraph-media-blog:http://siggraphmediablog.blogspot.com/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-the-media:node/5',
  );
  // Exported menu link: main-menu_speaker-preparation-room:node/25
  $menu_links['main-menu_speaker-preparation-room:node/25'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/25',
    'router_path' => 'node/%',
    'link_title' => 'Speaker Preparation Room',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_speaker-preparation-room:node/25',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_speaker-preparation:node/24',
  );
  // Exported menu link: main-menu_speaker-preparation:node/24
  $menu_links['main-menu_speaker-preparation:node/24'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/24',
    'router_path' => 'node/%',
    'link_title' => 'Speaker Preparation',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_speaker-preparation:node/24',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-presenters:node/16',
  );
  // Exported menu link: main-menu_sponsorship--advertising:node/129
  $menu_links['main-menu_sponsorship--advertising:node/129'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/129',
    'router_path' => 'node/%',
    'link_title' => 'Sponsorship & Advertising',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_sponsorship--advertising:node/129',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-exhibitors--advertisers:node/6',
  );
  // Exported menu link: main-menu_student-volunteers:node/48
  $menu_links['main-menu_student-volunteers:node/48'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/48',
    'router_path' => 'node/%',
    'link_title' => 'Student Volunteers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_student-volunteers:node/48',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-volunteers:node/3982',
  );
  // Exported menu link: main-menu_studio:node/90
  $menu_links['main-menu_studio:node/90'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/90',
    'router_path' => 'node/%',
    'link_title' => 'Studio',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_studio:node/90',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_studio:node/99
  $menu_links['main-menu_studio:node/99'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/99',
    'router_path' => 'node/%',
    'link_title' => 'Studio',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_studio:node/99',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_submitters-col-1:<nolink>
  $menu_links['main-menu_submitters-col-1:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Submitters-Col-1',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
          1 => 'hidden',
        ),
      ),
      'identifier' => 'main-menu_submitters-col-1:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-submitters:node/3',
  );
  // Exported menu link: main-menu_submitters-col-2:<nolink>
  $menu_links['main-menu_submitters-col-2:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Submitters-Col-2',
    'options' => array(
      'identifier' => 'main-menu_submitters-col-2:<nolink>',
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
          1 => 'hidden',
        ),
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-submitters:node/3',
  );
  // Exported menu link: main-menu_submitters-col-3:<nolink>
  $menu_links['main-menu_submitters-col-3:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Submitters-Col-3',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'menu-nolink',
          1 => 'hidden',
        ),
      ),
      'identifier' => 'main-menu_submitters-col-3:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-submitters:node/3',
  );
  // Exported menu link: main-menu_submitters-important-dates:http://null
  $menu_links['main-menu_submitters-important-dates:http://null'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://null',
    'router_path' => '',
    'link_title' => 'Submitters Important Dates',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_submitters-important-dates:http://null',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-1:<nolink>',
  );
  // Exported menu link: main-menu_submitters-important-message:http://null
  $menu_links['main-menu_submitters-important-message:http://null'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://null',
    'router_path' => '',
    'link_title' => 'Submitters Important Message',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_submitters-important-message:http://null',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-1:<nolink>',
  );
  // Exported menu link: main-menu_talks:node/80
  $menu_links['main-menu_talks:node/80'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/80',
    'router_path' => 'node/%',
    'link_title' => 'Talks',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_talks:node/80',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_talks:node/91
  $menu_links['main-menu_talks:node/91'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/91',
    'router_path' => 'node/%',
    'link_title' => 'Talks',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_talks:node/91',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_team-leaders:node/52
  $menu_links['main-menu_team-leaders:node/52'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/52',
    'router_path' => 'node/%',
    'link_title' => 'Team Leaders',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_team-leaders:node/52',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_student-volunteers:node/48',
  );
  // Exported menu link: main-menu_technical-papers-fast-forward:node/1026
  $menu_links['main-menu_technical-papers-fast-forward:node/1026'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1026',
    'router_path' => 'node/%',
    'link_title' => 'Technical Papers Fast Forward',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_technical-papers-fast-forward:node/1026',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_technical-papers:node/37
  $menu_links['main-menu_technical-papers:node/37'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'Technical Papers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_technical-papers:node/37',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_submitters-col-3:<nolink>',
  );
  // Exported menu link: main-menu_technical-papers:node/92
  $menu_links['main-menu_technical-papers:node/92'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/92',
    'router_path' => 'node/%',
    'link_title' => 'Technical Papers',
    'options' => array(
      'attributes' => array(),
      'alter' => TRUE,
      'identifier' => 'main-menu_technical-papers:node/92',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_attendees-col-3:<nolink>',
  );
  // Exported menu link: main-menu_travel-and-housing-assistance:node/3983
  $menu_links['main-menu_travel-and-housing-assistance:node/3983'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/3983',
    'router_path' => 'node/%',
    'link_title' => 'Travel and Housing Assistance',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_travel-and-housing-assistance:node/3983',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_student-volunteers:node/48',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('ACM SIGGRAPH Awards');
  t('ACM Student Research Competition');
  t('Art Gallery');
  t('Art Papers');
  t('Art Papers Reviewer Instructions');
  t('Attendees-Col-1');
  t('Attendees-Col-3');
  t('Birds of a Feather');
  t('Co-Located Events');
  t('Computer Animation Festival');
  t('Conference Overview');
  t('Contact the Media Office');
  t('Courses');
  t('Dailies');
  t('Education Focus');
  t('Electronic Slides and Still Images');
  t('Emerging Technologies');
  t('English Review Service');
  t('Equipment Insurance');
  t('Ethics of Review');
  t('Ethics of the Art Papers Review Process');
  t('Exhibiting at SIGGRAPH 2015');
  t('Exhibition');
  t('Exhibitor Tech Talks');
  t('Exhibits Fast Forward');
  t('For Attendees');
  t('For Exhibitors & Advertisers');
  t('For Presenters');
  t('For Submitters');
  t('For Volunteers');
  t('For the Media');
  t('Frequently Asked Questions');
  t('Future Conference Committees');
  t('Games Focus');
  t('GraphicsNet');
  t('Home');
  t('Hotels');
  t('How to Apply for a Visa');
  t('Information & Planning');
  t('International Resources');
  t('Job Fair');
  t('Job Seekers & Casual Networkers');
  t('Logos & Guidelines');
  t('Los Angeles');
  t('Making @ SIGGRAPH 2015');
  t('Mobile Focus');
  t('Movies in Presentations');
  t('News Releases');
  t('Panels');
  t('Posters');
  t('Production Sessions');
  t('Programs & Events');
  t('Publication Requirements');
  t('Real-Time Live!');
  t('Reasons to Attend SIGGRAPH');
  t('Recognition Policy for Presenters & Volunteers');
  t('Registration');
  t('Representative Image Guidelines');
  t('Reviewer Instructions');
  t('SIGGRAPH Media Blog');
  t('SIGGRAPH in the News');
  t('Session Room Equipment');
  t('Speaker Preparation');
  t('Speaker Preparation Room');
  t('Sponsorship & Advertising');
  t('Student Volunteers');
  t('Studio');
  t('Submitters Important Dates');
  t('Submitters Important Message');
  t('Submitters-Col-1');
  t('Submitters-Col-2');
  t('Submitters-Col-3');
  t('Talks');
  t('Team Leaders');
  t('Technical Papers');
  t('Technical Papers Fast Forward');
  t('Travel and Housing Assistance');


  return $menu_links;
}
