// Generated by CoffeeScript 1.8.0
(function() {
  var $;

  $ = jQuery;

  $(document).ready(function() {
    return $('.blue-reg-button').click(function() {
      var _gaq;
      _gaq = _gaq || [];
      _gaq.push(['send', 'event', 'Site Exit', 'Registration', '2015 Conference']);
      return window.open('https://register.rcsreg.com/r2/siggraph2015/', '_blank');
    });
  });

}).call(this);
